### ISSUE TITLE
Table 1 in the main paper: Tracking, Mapping and FPS

### ISSUE THREAD

**Issue by random-guest** [HengyiWang/Co-SLAM#21]
Dr. authors,

I understand that, please correct me if I am wrong, in Co-SLAM, tracking has to wait for mapping to complete first.

Therefore, the total time the system takes to map and track a single frame is defined by the tracking time.

Therefore, the FPS will not take into account the mapping time.

Therefore, it makes sense that tracking time should be larger than mapping time since it should include the mapping time. right?

But, I noticed that in Table 1 in the main paper, for the Replica dataset, the tracking time was less than that of the mapping (58 ms to 99 ms), yet the total FPS was counted based on the tracking time only.

Could you please clear this out for me?

Thank you in advance for your time and effort in answering my question.

**Comment by JingwenWang95** [comment]
Hi @random-guest  Actually your understanding is not correct. As mentioned in my previous [reply](https://github.com/HengyiWang/Co-SLAM/issues/13#issuecomment-1620273744), the FPS is the theoretical throughput under a perfect multi-processing scnerio. In Co-SLAM we run tracking at every frame but mapping **only every 5 frames**. As we assume a perfect multi-processing scenerio, mapping time will not present as bottleneck as long as it can finish within 5x tracking time, that's why here the FPS is counted based on tracking time only. But for NICE-SLAM, in most cases mapping is the bottleneck, that's why the way of calculating is different. Please refer to my previous answer for more details.
