### ISSUE TITLE
Tracking Error

### ISSUE THREAD

**Issue by mohcenaouadj** [HengyiWang/Co-SLAM#50]

**Comment by HengyiWang** [comment]
I would suggest doing a visualization of online mapping or just saving mesh every 50 frames to see what is going on. As you need a detailed reconstruction with 200 frames, you might want to increase the #pixels in the keyframe database instead of just using 5%.  (btw, are these two meshes extracted using the same voxel size?)

**Comment by mohcenaouadj** [comment]
.

**Comment by HengyiWang** [comment]
Yes, that makes sense because your first frame pose would not be changed so you basically just overfitting on it. In that case, the PSNR will be high. And PSNR is a metric that is super sensitive to the inaccuracy of the camera pose (Maybe also look into SSIM, LPIPs). For tracking, I think in MonoGS (https://arxiv.org/pdf/2312.06741, https://github.com/muskie82/MonoGS) they have done an analysis on Neural SDF, you may want to have a look.

**Comment by HengyiWang** [comment]
If you want to have a lower dependence on depth, you may need to change the rendering pipeline (VolSDF for instance). For questions regarding the truncation distance, check this thread and the related links https://github.com/HengyiWang/Co-SLAM/issues/2
