### ISSUE TITLE
reconstruction

### ISSUE THREAD

**Issue by mohcenaouadj** [HengyiWang/Co-SLAM#53]

**Comment by HengyiWang** [comment]
Hi @mohcenaouadj,

That is a great question. In fact, since you already know that you only have one object around the center, you can do a good initialization of the SDF field. In our new paper MorpheuS, we initialize the SDF into an approximate sphere using something similar to https://arxiv.org/abs/2002.10099. I think you can try this implicit initialization or just use a fixed blob function and let the model fit the SDF residual.

**Comment by mohcenaouadj** [comment]
@HengyiWang thank you a lot for your answer

**Comment by HengyiWang** [comment]
This is because the coordinate encoding is continuous. With the inherent smoothness of MLPs, once you start to train the model, it can have some sort of extrapolation (It naturally fits indoor scene reconstruction as most parts of the scene are flat (floor, wall, etc).

**Comment by mohcenaouadj** [comment]
Thanks a lot
