### ISSUE TITLE
When to release data capture by azure KinectDK?

### ISSUE THREAD

**Issue by zhangzscn** [HengyiWang/Co-SLAM#9]

**Comment by HengyiWang** [comment]
Hi @zhangzscn, thanks for your interest in our work. For the Azure dataset, we use the apartment data provided by NICE-SLAM instead of capturing data on our own. However, we do have the data captured by a real sense camera,  you can find it in our benchmark repo https://github.com/JingwenWang95/neural_slam_eval. And we will also release the tutorials for realsense later.
